apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: howler
  namespace: cluster-config
spec:
  # chart:
  #   spec:
  #     version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: howler.production
          paths:
            - path: /
              pathType: ImplementationSpecific
