apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: howler
  namespace: howler
spec:
  targetNamespace: howler
  releaseName: howler
  chart:
    spec:
      chart: howler-chart
      sourceRef:
        kind: HelmChart
        name: howler-chart
  interval: 5m
  install:
    remediation:
      retries: 3
