apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: howler
  namespace: howler
spec:
  targetNamespace: howler
  releaseName: howler
  chartRef: howler-chart
  interval: 5m
  install:
    remediation:
      retries: 3
