apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: howler
  namespace: cluster-config
spec:
  targetNamespace: howler
  releaseName: howler
  chart:
    spec:
      chart: howler-helm
      sourceRef:
        kind: GitRepository
        name: howler-repo
  interval: 5m
  install:
    remediation:
      retries: 3
